/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainView.java
 *
 * Created on Apr 19, 2011, 9:48:49 AM
 */

package com.sample.app;

import org.github.bouba.fumoffu.ActionManager;
import org.github.bouba.fumoffu.UIActions;

/**
 *
 * @author bouba
 */
public class MainView extends javax.swing.JFrame {

    /** Creates new form MainView */
    public MainView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        myButton = new javax.swing.JButton();
        myLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        myPanel.setName("myPanel"); // NOI18N

        myButton.setLabel("Click on me");
        myButton.setName("myButton"); // NOI18N
        myButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButtonActionPerformed(evt);
            }
        });
        myPanel.add(myButton);

        myLabel.setText("Some Text");
        myLabel.setName("myLabel"); // NOI18N
        myPanel.add(myLabel);

        getContentPane().add(myPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButtonActionPerformed
        this.am.handleAction(evt, UIActions.SAMPLE_ACTION, rootPane);
    }//GEN-LAST:event_myButtonActionPerformed

    ActionManager am;

    public MainView(ActionManager am) {
        this();
        this.am = am;
    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton myButton;
    private javax.swing.JLabel myLabel;
    private javax.swing.JPanel myPanel;
    // End of variables declaration//GEN-END:variables

}
